### ISSUE TITLE
Build xsbt-web-plugin for Scala 2.11 and 2.12

### ISSUE THREAD

**Issue by earldouglas** [earldouglas/xsbt-web-plugin#166]
Note: This [can't happen until sbt ~0.14~ 1.0][1].

[1]: http://stackoverflow.com/questions/23282469/does-sbt-builds-againts-scala-2-11

**Comment by psfblair** [comment]
Looks like sbt is now at 1.0.0-M4. Any progress on this?

**Comment by cdow** [comment]
There isn't going to be an sbt 0.14 release. The next release will be 1.0. This is still dependent on sbt doing a new final release.  1.0.0-M4 is a milestone release so it probably doesn't make sense to build against.

**Comment by psfblair** [comment]
Sorry, for some reason when I got M4 I thought it was a release candidate. My bad.

**Comment by xuwei-k** [comment]
WIP https://github.com/xuwei-k/xsbt-web-plugin/commit/97053f0fde7e81328042c3cef7b325dfb584ea3c

depends on https://github.com/earldouglas/xsbt-web-plugin/pull/348 and https://github.com/earldouglas/xsbt-web-plugin/pull/349
