### ISSUE TITLE
Don't re-package when nothing has changed

### ISSUE THREAD

**Issue by earldouglas** [earldouglas/xsbt-web-plugin#188]
Subsequent `package` commands cause packaging to happen multiple times, but this shouldn't be the case when no watched content has changed.

**Comment by earldouglas** [comment]
Related: #236

**Comment by earldouglas** [comment]
[This](http://www.scala-sbt.org/0.13.5/docs/faq.html#how-can-a-task-avoid-redoing-work-if-the-input-files-are-unchanged) might be handy.

**Comment by markkrueger** [comment]
> How can a task avoid redoing work if the input files are unchanged?¶

 

Wait, that confuses me, isn't that the whole point of Sbt?

**Comment by earldouglas** [comment]
No, but it certainly is one of the handy features.

**Comment by earldouglas** [comment]
Fixed by #284.
