### ISSUE TITLE
Launch container with test resources

### ISSUE THREAD

**Issue by hcoles** [earldouglas/xsbt-web-plugin#199]
I have various configuration resources I'd like to use when testing the app locally with container:start, but do not wish to package them into the released war.

I'm unclear on if/how this can be achieved. Possibly this is obvious to someone with more experience of sbt.

I am currently using the embedded tomcat container.

Thanks

**Comment by earldouglas** [comment]
My recommendation is to treat `container:start` as a production-like environment, which has access to the same resources as any other production instance.

If you externalize your configuration (for reference, see [Spring's approach](http://docs.spring.io/spring/docs/4.1.6.RELEASE/spring-framework-reference/html/beans.html#beans-factory-placeholderconfigurer) to this), you can have your webapp select between different configurations (e.g. development, test, staging, production, etc.) via a selector (e.g. environment variable, configuration option passed to the container by sbt, etc.).

I've captured the documentation of configuration externalization in #239.
