### ISSUE TITLE
WarOverlay support

### ISSUE THREAD

**Issue by dozed** [earldouglas/xsbt-web-plugin#203]
There is a WarOverlayPlugin in scalatra-sbt, which could be a good addition to xsbt-web-plugin. Is there any interest in it? If so I could provide a PR.

For the source code see here: https://github.com/dozed/scalatra-sbt/blob/xsbt-web-1.0/src/main/scala/org/scalatra/sbt/WarOverlayPlugin.scala

**Comment by earldouglas** [comment]
> I never needed to use it in one of my projects, though I see that it is a useful technique.

I've never seen anyone use it either.  This is a strong case for not bothering to add the complexity of support.  Since nobody else is asking for this, I'm going to close it for now.

**Comment by Milyardo** [comment]
#179 currently aims to delegate configuration for WEB-INF/lib to sbt-assembly, you could generalize this task to support overlay with sbt-assembly. In fact with sbt-assembly will already essentially perform a webapp overlay with it's default configuration.

**Comment by karanjeets** [comment]
@earldouglas - I would like to post another use case for war overlays - https://github.com/USCDataScience/sparkler/blob/master/sparkler-ui/pom.xml#L66

^^ I am trying to port this to SBT. Your plugin is helpful to build a WAR but I can't go any further to use overlays

Hope this is a good use case to support this feature

**Comment by earldouglas** [comment]
@karanjeets Thanks for the link.  Let's reopen this.

**Comment by karanjeets** [comment]
Thanks, @earldouglas !!

**Comment by earldouglas** [comment]
Fixed by #907.  Will be included in version 5.0.0.
