### ISSUE TITLE
Create a setting for container port

### ISSUE THREAD

**Issue by dozed** [earldouglas/xsbt-web-plugin#204]
Is there a reason there is no setting for the container port anymore? Sometimes it is useful to be able to access the port from other tasks.

**Comment by gvdm** [comment]
Previously one could <set port in container.Configuration := 80" in the SBT console allowing you to run an instance on an arbitrary port. This was great for running different instances on the same machine where people are working on different git repos concurrently. Is there anyway to set the port from the SBT console?

**Comment by earldouglas** [comment]
This is now available in 1.1.0 via the [`AutoPlugin` feature](https://github.com/earldouglas/xsbt-web-plugin#experimental-autoplugin-feature):

*build.sbt:*

```scala
jettyPort in container := 9090

enablePlugins(XwpJetty)
```

**Comment by dozed** [comment]
Thanks!
