### ISSUE TITLE
Changes in src/main/webapp not picked up during container:start

### ISSUE THREAD

**Issue by janheise** [earldouglas/xsbt-web-plugin#208]
Hi, maybe this is a dumb question: in a project with version 0.7.0 of the plugin, during development (started jetty with container:start) when I changed a file in src/main/webapp (e.g. index.html), the changes got picked up and displayed. No need to restart. This does not work for me with version 1.0.0. Is this the correct behavior or a bug or am I personally doing something wrong?
I only use jetty() to configure the plugin, no additional settings. Maybe I'm missing something?

Thanks,
Jan

**Comment by janheise** [comment]
Thanks. I tried to have a look into this myself yesterday but with my limited knowledge about sbt and other stuff it's way over my head right now.

**Comment by janheise** [comment]
Just another addition: if running from the prepared directory, I think it might also be possible to use spring-loaded instead of JRebel to watch for .class changes.

**Comment by ediweissmann** [comment]
+1 
I've just upgraded to 1.0.0 and miss the fast edit-and-refresh workflow.

**Comment by earldouglas** [comment]
Sorry for the delay -- I've been super swamped.  I strongly agree with the need for a fast edit-and-refresh workflow, so I want to do what it takes to get there with the forked JVM model of 1.0.

**Comment by dozed** [comment]
Running `~prepare` updates the `target/webapp` folder on source changes. An update takes <1 sec for me, which is acceptable imo.

**Comment by janheise** [comment]
Hi dozed, maybe there is a misunderstanding: how does updating target/webapp solve this, if xsbt-web 1.0.0 with container:start serves pages from the packaged WAR and not from a directory? Did you change anything else or do you have a different workflow?

**Comment by ediweissmann** [comment]
@dozed Thanks, that works for me.

```
container:start
~prepare
```

**Comment by dozed** [comment]
@janheise `container:start` serves from `target/webapp` (`webappDest in webapp`), at least for me. Or do you have a different setup?

**Comment by janheise** [comment]
@dozed Thanks for your insight. I think I have the same setup. Somehow I missed ~prepare. I started out with 0.7.0 and it worked differently then. What surprises me though is that I was under the assumption from the sources that container:start serves from the packaged .WAR and not from target/webapp. Maybe another oversight ;-)
