### ISSUE TITLE
Unable to create a war file

### ISSUE THREAD

**Issue by j-unior** [earldouglas/xsbt-web-plugin#211]
I've just updated to 1.0.0 version, and I'm unable to se `packageWar` task in autocompletion. runnig `package` task led only to jar file creation. The same is true about yuicompressor sample project in tests, it packages to jar only. SBT version 0.13.6, Scala version 2.11.4

Got it, I needed to put `warSettings` in the end of my `build.sbt`. There is no info neither about `warSettings` nor `webappSettings` the docs.

**Comment by earldouglas** [comment]
Are you still running into trouble packaging the *.war* file?
