### ISSUE TITLE
Resource deletion is not detected on either container:start or webapp:prepare 

### ISSUE THREAD

**Issue by inbrain** [earldouglas/xsbt-web-plugin#215]
To reproduce it you should delete a resource in src/main/webapp (say index.html) and then restart container (or webapp:prepare). Resource will remain in target/webapp

**Comment by earldouglas** [comment]
Thanks for reporting this!

**Comment by dozed** [comment]
Maybe the https://github.com/sbt/sbt/blob/0.13/main/actions/src/main/scala/sbt/Sync.scala could be used here. It should be able to detect removals too.
