### ISSUE TITLE
Scala 2.11

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [earldouglas/xsbt-web-plugin#217]
In the doc it says as requirements:
- Scala 2.10.x
- SBT 0.13.x

I think it works with projects that a Scala 2.11 based, even though SBT itself uses Scala 2.10.

**Comment by earldouglas** [comment]
Good to know, thanks for the report!  I'll update the docs accordingly.

**Comment by cdow** [comment]
You should be able to use any version of Scala supported by SBT.  I think SBT 0.13.x supports back to at least 2.8.
