### ISSUE TITLE
How to debug with Eclipse and IDEA?

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [earldouglas/xsbt-web-plugin#218]
Related stackoverflow question:

http://stackoverflow.com/questions/28173935/whats-the-best-way-of-debug-with-eclipse-a-sbt-based-webapp

**Comment by earldouglas** [comment]
I don't use Eclipse or IDEA, so I have no good suggestions for this.  My best guess would be the same as posed in the linked question -- to use remote debugging.

**Comment by cdow** [comment]
As it currently stands, remote debugging is really the only option.

**Comment by DavidPerezIngeniero** [comment]
Remote debugging is not so bad, 

The only small inconvenience is that it requires 2 phases: start the server, and attach the debugger.

**Comment by cdow** [comment]
I'm actually experimenting with an idea to see if I can make this less annoying.  I'm trying to write a proxy server for the debugger that will hide the underlying application start/restart process.  Hopefully this will allow you to attach a debugger once and then restart the process as many times as you want without having to re-attach your debugger.  You can follow progress [here](https://github.com/cdow/sbt-debug-plugin) if you are interested.

**Comment by DavidPerezIngeniero** [comment]
Thanks cdow, it looks like promising! :-)

**Comment by haha1903** [comment]
can use 
        javaOptions in container ++= Seq(
          "-Xdebug",
          "-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005"
        ),

**Comment by earldouglas** [comment]
@haha1903 Bingo, that configuration works great!  I've added it to the readme: https://github.com/earldouglas/xsbt-web-plugin#attach-an-eclipse-debugger

**Comment by DavidPerezIngeniero** [comment]
With IDEA, the same config works also!
