### ISSUE TITLE
When starting my project, it cannot find compiled Scala classes

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [earldouglas/xsbt-web-plugin#219]
I'm using Scala 2.11, and I have a mixed Java/Scala webapp project.

The server starts correctly, but fails afterwards because it doesn't find Scala compiled class:

    java.lang.NoClassDefFoundError: Could not initialize class fcc.ima.web.InicializadorEntorno$

Where `InicializadorEntorno` is a scala object.

I've checked and in the folder `target/scala-2.11/classes/fcc/ima/web`, I can find `InicializadorEntorno$.class`.

How can I solve it?
Is it due to use Scala 2.11.5, instead of the recommended Scala 2.10.X?

**Comment by earldouglas** [comment]
Interesting.  I've not run into this myself, but I'll play a bit with objects and 2.11 to see if I can reproduce it.

Can you tell me more about how this object is being accessed?  Is it referenced in *web.xml*?  Is there a stack trace associated with the `NoClassDefFoundError`?

**Comment by DavidPerezIngeniero** [comment]
It is called during the initialization phase of the main servlet.

**Comment by DavidPerezIngeniero** [comment]
I've discovered that the problem doesn't have to do with this plugin.
I close the issue.
