### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by olegstepura** [earldouglas/xsbt-web-plugin#220]
There is no documentation on how to create an SSL-protected connection in 1.*:
Old version (<= 0.9) allowed to do
`ssl in container.Configuration := Some(("0.0.0.0", 443, "keystore.jks", "xxx", "xxx"))`

but seems like this option is gone. Can you please update documentation on how to achive same results in 1.0?!

Thanks!

**Comment by earldouglas** [comment]
Sure thing, I'll update the docs later this evening.  Thanks for bringing this to attention!

**Comment by olegstepura** [comment]
Also even that this is not connected to issue above, IMO adding such info to the readme would be very helpful to others since `scanDirectories` and many more options are now gone: https://groups.google.com/d/msg/liftweb/Zt-m1bXeLmM/y1XyxRIinfAJ

**Comment by olegstepura** [comment]
Also the very helpful option to reload container has gone. Is there any workaround for this?
In 0.9 it was very easy to reload container on sbt finding changes to some code via `~`:
`sbt 'project test' '~;container:start; container:reload /'`

It would be nice to add info about such things as well.

**Comment by earldouglas** [comment]
> In 0.9 it was very easy to reload container on sbt finding changes to some code via

You can now do this simply via `~container:start`.  See [here](https://github.com/earldouglas/xsbt-web-plugin#triggered-relaunch) for more info.

**Comment by olegstepura** [comment]
Does `~container:start` do the same as `container:reload` did? I mean `reload` might have been faster since it did not do this `stop;start` cycle. But I may be wrong, please correct me if this is the case.

**Comment by olegstepura** [comment]
I have another question related to forking - is there a way to prevent forking? On dev environment now there is an issue that if you close the terminal, the jetty instance is not closed and is still running. Trying to start the project second time causes `BindException`
```
2015-02-02 19:08:02.014:WARN:oejuc.AbstractLifeCycle:main: FAILED ServerConnector@75c56eb9{HTTP/1.1}{0.0.0.0:8000}: java.net.BindException: Address already in use: bind
java.net.BindException: Address already in use: bind
```

You have to go to task manager and kill the process manually.

**Comment by earldouglas** [comment]
There's no way around forking with 1.0.0 -- it's a fundamental feature.

There have already been a few requests to re-introduce support for non-forked containers, so I created #221 to capture the various use cases -- please feel free to add a comment so we can capture and organize it.

**Comment by earldouglas** [comment]
> Does `~container:start` do the same as `container:reload` did?

Essentially, yes.  Since it's a forked JVM, you may notice it's a bit more sluggish than before, but it's still the same idea -- when the code changes, kill the currently running container, rebuild the code, re-launch the container.

**Comment by earldouglas** [comment]
Well, I'm having trouble getting the [official Jetty configuration files](https://github.com/eclipse/jetty.project/tree/release-9.1/jetty-server/src/main/config/etc) to work as documented -- they keep complaining about `Object of class 'org.eclipse.jetty.server.Server' is not of type 'org.eclipse.jetty.util.ssl.SslContextFactory'` in *jetty-ssl.xml*.

Anyhow, assuming I could get my hands on functining Jetty config, here's how I'd enable HTTPS:

*build.sbt:*

```scala
jetty(args = Seq
    "--config", "jetty.xml"
  , "--config", "jetty-https.xml"
  , "--config", "jetty-ssl.xml"
))
```

**Comment by olegstepura** [comment]
> Anyhow, assuming I could get my hands on functining Jetty config, here's how I'd enable HTTPS

Thanks! Will you update the docs?

> #221 ... feel free to add a comment so we can capture and organize it.

Well, I think my issue requires a separate ticket since if it may be solved with the forked JVM - than it's ok to have it forked.

**Comment by olegstepura** [comment]
Created #222

**Comment by earldouglas** [comment]
> Thanks! Will you update the docs?

Great idea; will do.  I wish I could actually get it working before documenting it.

**Comment by olegstepura** [comment]
:+1:
