### ISSUE TITLE
Kill the forked instance when main sbt instance was closed

### ISSUE THREAD

**Issue by olegstepura** [earldouglas/xsbt-web-plugin#222]
On dev environment now there is an issue that if you close the terminal, the jetty instance is not closed and is still running. Trying to start the project second time causes `BindException`
```
2015-02-02 19:08:02.014:WARN:oejuc.AbstractLifeCycle:main: FAILED ServerConnector@75c56eb9{HTTP/1.1}{0.0.0.0:8000}: java.net.BindException: Address already in use: bind
java.net.BindException: Address already in use: bind
```
You have to go to task manager and kill the process manually to release the port (and clean memory =)

I suppose this may be solved with having the forked version of JVM, without being the main reason to re-introduce non-forked containers (#221)

**Comment by cdow** [comment]
When you say 'close the terminal', I assume you mean closing the terminal that SBT is running in, correct?  If so, do you have this problem if you exit SBT with 'Ctrl-d' or the 'exit' command?

**Comment by olegstepura** [comment]
I do use `~container:start` for triggered restart. This means a running version does not allow you to print `exit`, Ctrl-d does not work for me (in cygwin  on windows)

**Comment by olegstepura** [comment]
What I mean by 'closing terminal' is pressing red `x` button on cygwin window,  which closes the window, kills the running sbt inside, but does not kill the forked jetty.

**Comment by cdow** [comment]
Can press 'Enter' to stop the triggered restart and then exit SBT with 'Ctrl-d' or the 'exit' command

**Comment by earldouglas** [comment]
> Can press 'Enter' to stop the triggered restart and then exit SBT with 'Ctrl-d' or the 'exit' command?

This is what I would recommend as well.

**Comment by cdow** [comment]
If you run sbt in it in batch mode with the command `sbt '~container:start'` then you only have to press 'Enter' to stop it completely.

**Comment by ritschwumm** [comment]
a simple, portable way to achieve the desired behaviour (child dies when the parent does) is to create some ServerSocket in the parent, let the child JVM connect to that socket and do a blocking read on it in an extra Thread. as soon as the parent exits, the read will abort throwing an IOException and child knows it should die.

**Comment by earldouglas** [comment]
> Ctrl-d does not work for me (in cygwin on windows)

What about `<ctrl>` + `c`?

**Comment by olegstepura** [comment]
> What about `<ctrl> + c`?

is does not work

**Comment by earldouglas** [comment]
How frustrating!  I wonder if there's a way to designate process hierarchies in cygwin so that when the parent process dies, any forked children are also terminated.

**Comment by olegstepura** [comment]
Won't the approach by @ritschwumm work? https://github.com/earldouglas/xsbt-web-plugin/issues/222#issuecomment-72950295

**Comment by earldouglas** [comment]
Yes, I think it would work, but I'm concerned that it would add fragile complexity (e.g. reliance on a new port being available).

**Comment by olegstepura** [comment]
Hi! Was this fixed or is a won't fix?

**Comment by earldouglas** [comment]
Unfortunately this is a *won't fix*.  Are you frequently running into this issue?

**Comment by olegstepura** [comment]
Using old version again. This issue is the main reason.

**Comment by earldouglas** [comment]
I may have found a workaround.  Depending on how the process is being killed by closing the window, Java may be able to run an exit hook.  This works with a SIGINT in Linux:

*build.sbt:*

```scala
ContainerPlugin.start := {
  java.lang.Runtime.getRuntime().addShutdownHook(
    new java.lang.Thread("app-shutdown-hook") {
      override def run(): Unit = { 
        println("bye"); 
      }
  })
  (ContainerPlugin.start in Jetty).value
}
```

Can you try it with xsbt-web-plugin 2.0.0 in Windows and let me know if it works?  If this works, let's get it added to 2.0.1.

**Comment by earldouglas** [comment]
Edit: actually, you won't see that println statement because the window is closed.  Standby, I'm working on an approach for the Windows case.

**Comment by earldouglas** [comment]
Updated the above example. This should create a file called xsbt-web-plugin.log with the text killed! when you close the sbt window. If this works, I'll add similar code to 2.0.1 that shuts down the server when you close the sbt window.

**Comment by olegstepura** [comment]
Wanted to try this out, but I'm using scala configuration format and this
```scala

  val website = Project(
    id = "website",
    base = file("website"),
    settings = buildSettings ++ Seq(
      containerPort := 8000
    ),
    dependencies = Seq(core)
  ).enablePlugins(JettyPlugin)
```
leads to 
```
...
[info] Done packaging.
[info] starting server ...
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Unrecognized option: --port
```

**Comment by olegstepura** [comment]
Hi! I tried this out and there is no `xsbt-web-plugin.log` file nearby (not in project folder, not in temp, not in user home folder)

**Comment by earldouglas** [comment]
Thanks for trying it out.  It's frustrating that it's not working.  Can you confirm that Jetty is still running after you close the sbt window?  I tried this myself, and Jetty stopped successfully when running sbt from either cmd or git-bash.  I was unable to get sbt to run at all under cygwin.

**Comment by olegstepura** [comment]
I'm using cygwin. With version 0.* the main window just closed when clicking the close button of mintty (red x-button) after a confirmation that there is a process running inside. After version 1.* when clicking close it askes for confirmation, but on confirm doesn't close. It closes after second click and jetty process is still running. With version 2.0 it's the same. I can confirm, process is in TaskManger and same shell script for launching sbt with jetty cannot be started because the port is already in use. Also the website still responds when requesting via browser.

**Comment by iurisman** [comment]
Want to add my voice to the choir. SBT should absolutely cleanup when terminated, there's just no justification otherwise. The current behavior is counterintiutive and the complexity of finding the stray java proc far surpasses the competency is the typical SBT user.

In my case, I am starting a testProd process, which doesn't seem to be a subject to forking configuration and is always started in a subprocess. Which is cool, so long as the subprocess is cleaned up and highly not cool otherwise.
