### ISSUE TITLE
signer information does not match

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [earldouglas/xsbt-web-plugin#223]
When launching my server, I'm receiving this exception:

    class "org.apache.commons.io.output.ByteArrayOutputStream"'s signer information does not match signer information of other classes in the same package

In my app I use `commons-io % commons-io % 1.4`.
I've had to change to  `commons-io % commons-io % 2.4`, for this error to disappear.

Probably it clashes with Jetty `commons-io`.

**Comment by earldouglas** [comment]
Interesting, I wonder where that dependency is coming from.

Which container launcher are you using?  By default, jetty-runner 9.2.1 is used, but it doesn't have any *.jar* dependencies I'm aware of.

Which (if any) libraries do you have in the `"container"` configuration?

**Comment by DavidPerezIngeniero** [comment]
I'm using default container setup.

No `libraryDependencies` in the `container` configuration.

    lazy val servision = project.settings(com.earldouglas.xwp.XwpPlugin.jetty(port = 20610) ++ Seq(...))

**Comment by DavidPerezIngeniero** [comment]
Confirmed, `Jetty 9.2.1.v20140609` requires `commons-io-2.4.jar`.
If a `webapp` uses `commons-io-1.4`, then the above error is raised.

**Comment by earldouglas** [comment]
This should be [fixed](https://github.com/earldouglas/xsbt-web-plugin/commit/d1be71fa09bd91303d5d2ad664137f1558c6b131) in xsbt-web-plugin 1.1.0.  Can you confirm?

**Comment by earldouglas** [comment]
Closing.  Please re-open if this pops up again.

**Comment by DavidPerezIngeniero** [comment]
Confirmed that I don't see this error any more.
