### ISSUE TITLE
How to call container:start with different parameters?

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [earldouglas/xsbt-web-plugin#225]
I need to call `container:start` with different `javaOptions` from different tasks.

How can I get this easily?

Example:

    val init = taskKey[Process]("Start server")
    init := (start in (servision, container)).value

    lazy val servision = project.settings(
        javaOptions in container += "-Dmyvar=myvalue"
    )

I would like to create a 2nd task that calls container:start with other set of parameters.

**Comment by earldouglas** [comment]
This feels like it might be venturing outside the scope of the plugin.  Can you go into more detail about your use case?  What are the sets of options you'd like to apply between tasks?

**Comment by DavidPerezIngeniero** [comment]
For example, a configuration with remote debugging, another one without it.
And a 3rd one with a variable defined (`-Dmyvar=myvalue`).

A possible workaround is to use the `set` command of SBT to change the value of `javaOptions in container`.

**Comment by earldouglas** [comment]
You could write sbt commands for each different case, and let them apply their own custom settings:

*build.sbt:*

```scala
def foobar = Command.command("foobar") { state =>
  val state2 = Project.extract(state).append(Seq(javaOptions in container += "-Dfoo=bar"), state)
  Project.extract(state2).runTask(start in container, state2)
  state
}

commands += foobar

def foobaz = Command.command("foobaz") { state =>
  val state2 = Project.extract(state).append(Seq(javaOptions in container += "-Dfoo=baz"), state)
  Project.extract(state2).runTask(start in container, state2)
  state
}

commands += foobaz
```

Now from sbt you can run any of the following:

* `container:start`, for a regular container without the system property `foo` set
* `foobar`, for a container running with the system property `foo` set to `bar`
* `foobaz`, for a container running with the system property `foo` set to `baz`

**Comment by earldouglas** [comment]
Oops, accidentally closed the issue.  Reopened.

**Comment by DavidPerezIngeniero** [comment]
:-) Wow. It works!.  Thanks to your help, I've discovered the power of SBT commands.

In my case, I've preferred to create a parametrized command, in order to reduce redundance.
