### ISSUE TITLE
Make webappSrc, webappDest and webInfClasses Settings instead of Tasks

### ISSUE THREAD

**Issue by dozed** [earldouglas/xsbt-web-plugin#226]
Having those as settings would allow that other settings depend on them (in SBT a settings can't depend on a task). Imo there is no benefit of having them as as task here.

A simple use case is when you want to use webappDest to create a file filter with the absolute name of the directory (https://github.com/dozed/scalatra-sbt/blob/6845051835a49e9d2ecc7c951770ca288041be44/src/main/scala/org/scalatra/sbt/DistPlugin.scala#L98-L101).

**Comment by earldouglas** [comment]
This will break backward compatibility (see 0a0168e), so tagged this for the 2.0.0 release.
