### ISSUE TITLE
Publish latest release(s) to Maven?

### ISSUE THREAD

**Issue by kflorence** [earldouglas/xsbt-web-plugin#242]
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.earldouglas%22%20AND%20a%3A%22xsbt-web-plugin%22

Will you continue publishing releases to Maven? Or have you switched entirely to bintray?

**Comment by kflorence** [comment]
Alternatively, could you make your package available in JCenter? https://bintray.com/bintray/jcenter

**Comment by kflorence** [comment]
I see that it is available here: https://bintray.com/sbt/sbt-plugin-releases -- this seems fine, but perhaps it can be documented in the README. I had to poke around for awhile to find it as I didn't want to have to add a repository specifically for this plugin.

**Comment by earldouglas** [comment]
You don't need to add any repositories to use xsbt-web-plugin, because sbt already knows to look at the sbt-plugin-releases repository.

If you check out the [starting from scratch](https://github.com/earldouglas/xsbt-web-plugin#starting-from-scratch) guide, you'll see that the only thing needed in your *plugins.sbt* is a call to `addSbtPlugin` -- no additions to `resolvers` is needed.

Are you having trouble resolving xsbt-web-plugin in your project without explicitly adding a bintray resolver?  If so, something strange is going on.

**Comment by kflorence** [comment]
@earldouglas ah, I see. If that's an sbt 0.13.5+ feature that would explain why resolving was working for me locally but not on the server (which has an older version of sbt -- we are mid-transition). No need to add anything to Maven in that case :)

**Comment by earldouglas** [comment]
Cool, glad to hear you got it working.  What version of sbt were you using, with which it was failing?  If this was only recently added (e.g. sbt 0.13.5+), I think we better get it documented loud and clear in the readme.

**Comment by kflorence** [comment]
0.13.2

On Wednesday, April 8, 2015, James Earl Douglas <notifications@github.com>
wrote:

> Cool, glad to hear you got it working. What version of sbt were you using,
> with which it was failing? If this was only recently added (e.g. sbt
> 0.13.5+), I think we better get it documented loud and clear in the readme.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/earldouglas/xsbt-web-plugin/issues/242#issuecomment-91109240>
> .
>


-- 
Kyle Florence
http://kflorence.com

**Comment by earldouglas** [comment]
Confirmed - requires at least 0.13.5.

Added to docs [here](https://github.com/earldouglas/xsbt-web-plugin/blob/master/README.md#requirements)

**Comment by kflorence** [comment]
Awesome. It seems like this is still a problem on our build server where we run a command like:

```shell
$ /usr/lib/jvm/java-7-oracle-amd64/bin/java -Xms512M -Xmx1280M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=512M -Dsbt.log.noformat=true -Dsbt.override.build.repos=true -Dsbt.repository.config=$WORKSPACE/sbt.repository.config -jar /usr/local/sbt-0.13.8/bin/sbt-launch.jar clean test package
```
and where our repository config is as follows:
```
[repositories]
  local
  maven-local
  typesafe-ivy-releases: http://art.intranet.solarmosaic.com/artifactory/typesafe-ivy/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
  maven-proxy-releases: http://art.intranet.solarmosaic.com/artifactory/sbt-maven-releases/
  internal-releases: http://art.intranet.solarmosaic.com/artifactory/internal-releases/
  scalaz-releases: http://art.intranet.solarmosaic.com/artifactory/scalaz-releases/
  internal: http://art.intranet.solarmosaic.com/artifactory/internal/
```

Results in:

12:30:20 [info] Resolving com.earldouglas#xsbt-web-plugin;1.1.0 ...
12:30:20 [warn] 	module not found: com.earldouglas#xsbt-web-plugin;1.1.0

However if I explicitly add the `sbt-plugin-releases` to the repository config, it works:

```
sbt-plugin-releases: http://art.intranet.solarmosaic.com/artifactory/sbt-plugin-releases/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
```

Wonder if it's a problem with sbt-launch.jar

**Comment by earldouglas** [comment]
Can you add the *sbt-plugin-releases* repo to your server's *sbt.repository.config* file?

**Comment by kflorence** [comment]
@earldouglas yeah, that's the fix I'm using now (see above post) -- it works if I add it explicitly, but otherwise it can't find it.

**Comment by earldouglas** [comment]
Sorry, I'm not quite understanding the problem.  The purpose of the `-Dsbt.override.build.repos=true` setting is to disable sbt's built-in resolvers, so you will need to add *sbt-plugin-releases* manually to be able to resolve xsbt-web-plugin.

From *http://www.scala-sbt.org/0.13/docs/Proxy-Repositories.html*:

> This setting is used to specify that all sbt project added resolvers should be ignored in favor of those configured in the repositories configuration. Using this with a properly configured ~/.sbt/repositories file leads to only your proxy repository used for builds.

Is this not the behavior you're expecting?

**Comment by kflorence** [comment]
@earldouglas ah, I didn't catch that parameter (I did not set up the build server myself) -- good to know, and sorry for the bother :)

**Comment by earldouglas** [comment]
Cool, glad you figured it out!

**Comment by mqshen** [comment]
I use sbt launcher version 0.13.7 but I also has the error 
    
    [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
    [warn] 	::          UNRESOLVED DEPENDENCIES         ::
    [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
    [warn] 	:: com.earldouglas#xsbt-web-plugin;1.1.0: not found
    [warn] 	::::::::::::::::::::::::::::::::::::::::::::::

**Comment by earldouglas** [comment]
@mqshen This sounds like a problem with your resolvers.  Can you post the full output, including error messages about which servers were searched?

**Comment by mqshen** [comment]
I add the https://dl.bintray.com/sbt/sbt-plugin-releases/ to my repositories and it works.
thx!
