### ISSUE TITLE
Remove `webapp` config

### ISSUE THREAD

**Issue by guersam** [earldouglas/xsbt-web-plugin#243]
xsbt-web-plugin introduces two configs, `container` and `webapp`. The former is closely related to downloading/launching (maybe deploying in the future) with additional dependencies, therefore it deserves to have a separate config [1]. On the other hand, the latter behaves more like a namespace than separate configuration, although it's basically related to already existing task `package`.

SBT discourages using a configuration as namespace [2]:  
> Configurations should not be used to namespace keys for a plugin. If you’re merely adding tasks and settings, don’t define your own configuration. Instead, reuse an existing one or scope by the main task (see below).

Having `webapp` as a config makes it harder to separate dev/prod environment profile as discussed in #199. if packaging-related tasks just depend on current scope instead of using hardcoded configuration, it'll be much easier to assign different settings according to user-defined config.

[1] http://www.scala-sbt.org/0.13/docs/Plugins-Best-Practices.html#When+to+define+your+own+configuration
[2] http://www.scala-sbt.org/0.13/docs/Plugins-Best-Practices.html#You+probably+won%E2%80%99t+need+your+own+configuration

**Comment by earldouglas** [comment]
:+1:

**Comment by guersam** [comment]
Great :) I'll open a PR for v2 branch within a couple of days, with additional best practices in SBT doc for further discussion.
