### ISSUE TITLE
Profile/configuration for webapp plugin

### ISSUE THREAD

**Issue by aardelean** [earldouglas/xsbt-web-plugin#245]
Hi,

 I have successfully configured your plugin in a war application. My only problem is that if I create a new config/profile in sbt, dev, the dev:package doesn't consider the dev's config parameters.

```
 val ProfileDev = config("dev") extend(Runtime)

 val root = (project in file(".")).
 configs(ProfileDev).
 settings(
 ).
 settings(inConfig(ProfileDev)(Classpaths.configSettings ++ Defaults.configTasks ++ Defaults.resourceConfigPaths ++ Seq(
 unmanagedResourceDirectories += {baseDirectory.value / "src" / configuration.value.name / "resources"}
 )): _*)
```

 And then go to sbt and type `dev:package`. The jar is not containing the proper config files.

 same goes for adding

```
 unmanagedResourceDirectories in ProfileDev <+= (sourceDirectory in Compile)(_ / "extra")
```

 Is there no way to change the config for package task? Looks like it executes the task just from the Compile configuration. Am I correct?

 Best Regards, Alexandru.

**Comment by earldouglas** [comment]
It looks like [this](http://stackoverflow.com/a/20573422) is what you want, but I can't get it working with sbt 0.13.7.

**Comment by guersam** [comment]
It should work with current 2.0 branch, but I haven't tested yet.

**Comment by aardelean** [comment]
Ok, thanks!

**Comment by earldouglas** [comment]
2.0.1 is now available; can you give it a try?
