### ISSUE TITLE
Compilation of static files requires a server restart

### ISSUE THREAD

**Issue by alexflav23** [earldouglas/xsbt-web-plugin#246]
As a long time user of the xsbt-web-plugin, I've upgraded a project to the most recent version. There seem to be significant changes(coming from 0.7.0), but one in particular I can't wrap my head around.

We auto-generate/compile a variety of files in the project, mainly less and JavaScript files, but unlike before, now every single time less files and JS files are compiled a full server reload is required. I wanted to understand if this is indeed the case of if I am mis-using the new plugin API.

**Comment by earldouglas** [comment]
You're right, this is indeed the case.  It's mostly a side-effect of how we're more "properly" serving the content now, in an attempt to more closely mimic a production environment.

I want development speed to be as rapid as possible, so this is an issue I'd like to address.  It is related to https://github.com/earldouglas/xsbt-web-plugin/issues/236, and could ideally be fixed in 2.0, which will be out in a [few months](https://github.com/earldouglas/xsbt-web-plugin/milestones).

**Comment by aindlq** [comment]
I would say this feature is a must have. @alexflav23 Could you please describe how you have achieved this in the old version? I've downgraded to 0.9 and specify directory with my assets: ```webappResources in Compile <+= (sourceDirectory in Runtime)(sd => myasstestdir)```
but when change some asset, jetty doesn't pickup the change.

**Comment by earldouglas** [comment]
If folks are downgrading just for this feature, it's a pretty clear signal.  Let's get this into 2.0.

**Comment by earldouglas** [comment]
This will be supported in 2.0.0, which will be released in the next day or two.  The process will be to start the container, make some changes, then prepare the Web app again.  This last step can be automatically triggered on changes:

```
> jetty:start
> ~webappPrepare
```

**Comment by earldouglas** [comment]
D'oh, the comment above was meant for the "static resources" issue, not this one.  Sorry for the mistake!

**Comment by earldouglas** [comment]
I think your best bet for runtime recompilation of code is to use JRebel.  Check out the [docs](https://github.com/earldouglas/xsbt-web-plugin/blob/master/docs/1.1.1.md#using-jrebel) for more info.

**Comment by earldouglas** [comment]
Please disregard my earlier response -- it was meant for a different issue.  This is why I shouldn't do issue tracking while tired. :]

**Comment by earldouglas** [comment]
Check out [quickstart mode][1], now available in xsbt-web-plugin 2.3.0.

[1]: https://github.com/earldouglas/xsbt-web-plugin/blob/2.3.0/docs/2.3.md#quickstart-mode
