### ISSUE TITLE
Upgraded to 1.1.0 and container no longer searching "unmangedClasspath in Runtime"

### ISSUE THREAD

**Issue by hughgearse** [earldouglas/xsbt-web-plugin#248]
I have a project that refers to classes in another project. To facilitate this I have added the following two lines to my build.scala settings:

      unmanagedClasspath in Compile += file("/path/to/my/classes"),
      unmanagedClasspath in Runtime += file("/path/to/my/classes"),

This worked fine when using version 0.9.0 of the plugin. But when I upgraded to version 1.1.0 I get a java.lang.NoClassDefFoundError whenever I try to reference a class in this project.

Note: I am using it in conjunction with scalatra-sbt. So it worked fine with 

addSbtPlugin("com.earldouglas" % "xsbt-web-plugin" % "0.9.0")
addSbtPlugin("org.scalatra.sbt" % "scalatra-sbt" % "0.3.5")

But when I changed up to 1.1.0 and 0.4.0 respectively I started to get the NoClassDefFoundError.

**Comment by earldouglas** [comment]
Regardless of xsbt-web-plugin, do the classes in `"/path/to/my/classes"` get included in your project's *.jar* file when you `package` it?

It could be that they're only made available during compilation and runtime in sbt, which would explain why they're not seen by xsbt-web-plugin, which uses the `package` artifact to run your application.

**Comment by hughgearse** [comment]
Yes it is not including any of the classes in the war file (the jar file only has the classes for the project itself). I tested it with version 0.9.0 and in that case all the classes do get added to the war file when I run the package command.

**Comment by earldouglas** [comment]
You'll need to find a way to get your *.class* files included in the *.jar* package that sbt creates.  One way is to tell sbt that they are unmanaged resources:

```scala
unmanagedResourceDirectories in Compile += baseDirectory.value / "myclasses"
```
