### ISSUE TITLE
is 1.2.0 working?

### ISSUE THREAD

**Issue by jamerlan** [earldouglas/xsbt-web-plugin#256]
I have a project which was working with 1.1.0 version of plugin. When I changed to 1.2.0 - not its not building. 
I have sbt 0.13.7

[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.earldouglas#xsbt-web-plugin;1.2.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.earldouglas:xsbt-web-plugin:1.2.0 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          com.earldouglas:xsbt-web-plugin:1.2.0 (scalaVersion=2.10, sbtVersion=0.13) (/home/revenant/projects/springrts-ru-website/project/plugins.sbt#L3-4)
[warn]            +- default:springrts-ru-website-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: com.earldouglas#xsbt-web-plugin;1.2.0: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:291)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:188)

**Comment by earldouglas** [comment]
The latest release is *1.1.1* -- there hasn't been a *1.2.0* quite yet.  We did briefly test a milestone release of *1.2.0-M1* for #250, but those changes are now rolled up into *1.1.1*.

**Comment by jamerlan** [comment]
why website "https://github.com/earldouglas/xsbt-web-plugin" suggests to use 1.2.0 then?

**Comment by earldouglas** [comment]
Oops, sorry about that!  That was a typo.  Should be fixed now.
