### ISSUE TITLE
How to disable the exit hook?

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [earldouglas/xsbt-web-plugin#262]
I've observed that when SBT quits, the started server is terminated.
How can I disable this behaviour?
I've seen an exit hook is set up.

I would make a setting for controlling this.

**Comment by earldouglas** [comment]
This is a great idea.  I don't think there's an easy way to do it, so I will add a setting.

An ugly way would be to manually clear all the exit hooks before you start your container:

*build.sbt:*

```scala
commands += Command.command("runExitHooks")(s: State => s.runExitHooks())
```

*sbt:*

```
> runExitHooks
> container:start
> exit
```

**Comment by earldouglas** [comment]
I added this to the upcoming 2.0.0 release, which should be out in the next day or two.  You will be able to use it to tell sbt not to shutdown the container when sbt exits:

```scala
containerShutdownOnExit := false
```

**Comment by DavidPerezIngeniero** [comment]
That's good news.  In this way, there's no need to fork it.
Thanks Earl!

**Comment by DavidPerezIngeniero** [comment]
Is there a way that I can test it?

**Comment by earldouglas** [comment]
[Here's the documentation](https://github.com/earldouglas/xsbt-web-plugin/blob/master/docs/2.0.0.md#container-shutdown-and-sbt) for this feature.  Cheers!
