### ISSUE TITLE
Publish war regression in 2.0.1

### ISSUE THREAD

**Issue by fedgehog** [earldouglas/xsbt-web-plugin#270]
publish/publishLocal publishes everything except war file in latest version. 

Here is the output for publishLocal using plugin version 2.0.1:
published package-regression-sample_2.10 to .../poms/package-regression-sample_2.10.pom
published package-regression-sample_2.10 to .../jars/package-regression-sample_2.10.jar
published package-regression-sample_2.10 to .../srcs/package-regression-sample_2.10-sources.jar
published package-regression-sample_2.10 to .../docs/package-regression-sample_2.10-javadoc.jar 

That's output for publishLocal using plugin version 1.1.1:
published package-regression-sample_2.10 to .../jars/package-regression-sample_2.10.jar
published package-regression-sample_2.10 to .../docs/package-regression-sample_2.10-javadoc.jar
published package-regression-sample_2.10 to .../poms/package-regression-sample_2.10.pom
published package-regression-sample_2.10 to .../wars/package-regression-sample_2.10.war
published package-regression-sample_2.10 to .../srcs/package-regression-sample_2.10-sources.jar

**Comment by fedgehog** [comment]
Minimal setup to reproduce can be found here https://www.dropbox.com/s/f3tmyx677nz5sya/publish-regression.zip?dl=0

**Comment by earldouglas** [comment]
Yikes, that's a big regression.  Thanks for the report!

**Comment by earldouglas** [comment]
Should be fixed now in *2.0.2*.
