### ISSUE TITLE
Problem setting jetty version

### ISSUE THREAD

**Issue by davenatx** [earldouglas/xsbt-web-plugin#272]
Hi:

I am using version 2.0.2.  Everything works great however, when I attempt to change the version of Jetty following the documentation here: 

https://github.com/earldouglas/xsbt-web-plugin/blob/master/docs/2.0.md#jetty-version 

It seems to ignore the version I specify.  I pulled down the container/jetty-9 example and also had the same issue.  After making this change:
```
containerLibs := Seq("org.eclipse.jetty" % "jetty-runner" % "9.3.0.v20150714" intransitive())
```
I reloaded SBT and did jetty:start.  I see the following in SBT:
```
2015-07-20 18:08:29.376:INFO:oejr.Runner:main: Runner
2015-07-20 18:08:29.496:INFO:oejs.Server:main: jetty-9.2.1.v20140609
```

**Comment by earldouglas** [comment]
Oops, that's a bug in the documentation.  Try adding `in Jetty`:

```scala
containerLibs in Jetty := Seq("org.eclipse.jetty" % "jetty-runner" % "9.3.0.v20150714" intransitive())
```

**Comment by davenatx** [comment]
That did it.  Thanks!
