### ISSUE TITLE
Publising to nexus artifactory

### ISSUE THREAD

**Issue by wilmveel** [earldouglas/xsbt-web-plugin#274]
We are using het xsbt-web-plugin to package our spray app into a war file. When we publish to the nexus enviroment not the war file but the jar is uploaded.

**Comment by earldouglas** [comment]
Are you using version 2.0.1?  If so, this was fixed (issue #270) in version 2.0.2.

**Comment by wilmveel** [comment]
We are using 2.0.2. it does publish te war file to nexus. When we download the file back from nexus after it has been uploaded it has the content of the jar file. Looks like jar and war are switched somewhere.

**Comment by wilmveel** [comment]
I found this code snipt online. Maybe I is missing the part where it creates the Artifact for publishing the war.

````
// create an Artifact for publishing the .war file
artifact in (Compile, packageWar) ~= { (art: Artifact) =>
  art.copy(`type` = "war", extension = "war")
}

// add the .war file to what gets published
addArtifact(artifact in (Compile, packageWar), packageWar)

````

**Comment by wilmveel** [comment]
I found the problem:

Can you change:
 
addArtifact(artifact in (Compile, pkg), pkg in Compile)

into

addArtifact(artifact in (Compile, pkg), pkg)

**Comment by earldouglas** [comment]
Ah ha, of course!  Thanks for catching that.  Stand by for a fix...

**Comment by earldouglas** [comment]
Can you give 2.0.3 a try?

**Comment by wilmveel** [comment]
Tnx, works like a charm
