### ISSUE TITLE
packageOptions in packageWar does not exist

### ISSUE THREAD

**Issue by omervk** [earldouglas/xsbt-web-plugin#277]
Hi,

I'm trying to follow the [readme file for version 2.0](https://github.com/earldouglas/xsbt-web-plugin/blob/master/docs/2.0.md) and a part there says I can add manifest attributes to the WAR file by using:

    packageOptions in packageWar += Package.ManifestAttributes( java.util.jar.Attributes.Name.SEALED -> "true" )

Unfortunately, this causes an error ```not found: value packageWar```. I tried alternatively using:

    packageOptions in (Compile, packageBin) += Package.ManifestAttributes( java.util.jar.Attributes.Name.SEALED -> "true" )

Which the docs say will cause the value to be "changed in both artifacts", but that only changes the JAR's manifest.

I'd love to know what I'm doing wrong here...
Thanks.

**Comment by earldouglas** [comment]
This is a bug in the documentation -- thanks for catching it.  Try the following, and if it works for you I'll update the docs:

To add manifest attributes to the *.war* file:

```scala
packageOptions in (Compile, sbt.Keys.`package`) +=
  Package.ManifestAttributes( java.util.jar.Attributes.Name.SEALED -> "true" )
```

To add manifest attributes to the *.jar* file:

```scala
packageOptions in (Compile, packageBin) +=
  Package.ManifestAttributes( java.util.jar.Attributes.Name.SEALED -> "true" )
```

**Comment by earldouglas** [comment]
Oops, I spoke too soon.  It looks like the above `sbt.Keys.package` solution isn't working all the time for me.  Stand by...

**Comment by omervk** [comment]
Great, that works! Thanks :)

**Comment by earldouglas** [comment]
Great!  Docs updated:

https://github.com/earldouglas/xsbt-web-plugin/blob/master/docs/2.0.md#add-manifest-attributes

**Comment by omervk** [comment]
Thanks! And thank you for this plugin - I've been using it on-and-off for a few years now and am very thankful for your work :bow:
