### ISSUE TITLE
MANIFEST in WAR is not the same as in JAR

### ISSUE THREAD

**Issue by phillipviana** [earldouglas/xsbt-web-plugin#278]
Hi,

First of all congratulations for the awesome plugin! :-)

I am very new to your plugin and sbt in general. I want the MANIFEST file in my WAR to have some metadata about the company and the  timestamp of when the build was generated. For example:

Manifest-Version: 1.0
Implementation-Vendor: org.mycompany
Implementation-Title: MyCompany Project
Implementation-Version: 1.0.0-20150909110435
Implementation-Vendor-Id: org.mycompany
Specification-Vendor: org.mycompany
Specification-Title: MyCompany Project
Specification-Version: 1.0.0-20150909110435

I was able to achieve that for the JAR (that is created by packageBin) using this configuration:

val baseVersion = SettingKey[String]("base-version",)

lazy val commonSettings = Seq(
  organization := "org.mycompany"
)

lazy val root = (project in file(".")).
  enablePlugins(WarPlugin).
  settings(commonSettings: _*).
  settings(
    name := "MyCompany Project",
    artifactName := { (sv: ScalaVersion, module: ModuleID, artifact: Artifact) =>
        artifact.name + "-" + baseVersion.value + "." + artifact.extension  
    },
    baseVersion := "1.0.0",
    crossTarget := new java.io.File("target"),
    version := new String(baseVersion.value) + "-" + new java.text.SimpleDateFormat("yyyyMMddHHmmss").format(new java.util.Date()).toString(),
    webappWebInfClasses := true
)

However, the WAR file created in package only contains "Manifest-Version: 1.0" in the MANIFEST.

Could you please advise?

**Comment by earldouglas** [comment]
I can't look deeply into this until later tonight, but for now, have you tried setting `packageOptions in sbt.Keys.`package``?

```scala
packageOptions in sbt.Keys.`package` +=
  Package.ManifestAttributes( java.util.jar.Attributes.Name.SEALED -> "true" )
```

See: https://github.com/earldouglas/xsbt-web-plugin/blob/master/docs/2.0.md#add-manifest-attributes`

**Comment by phillipviana** [comment]
Hi Douglas,

Thanks for the quick reply.

I have tried that option and sbt packages successfully, then my MANIFEST.MF file contains an extra line with "Sealed: true".

Manifest-Version: 1.0
Sealed: true

I understand that it is possible to manually add attributes this way. However, I thought the metadata would be included automatically in the MANIFEST just like it happens with the JAR. Or do I need to manually add all attributes in this case?

**Comment by earldouglas** [comment]
Give this a try.  It should tell sbt to add all `ManifestAttributes` from the *.jar* to the *.war*:

```scala
packageOptions in sbt.Keys.`package` ++=
  (packageOptions in (Compile, packageBin)).value filter {
    case x: Package.ManifestAttributes => true
    case x => false
  }
```

**Comment by earldouglas** [comment]
> However, I thought the metadata would be included automatically in the MANIFEST

Do you think this should be the default behavior of xsbt-web-plugin?  It sounds like a good idea to me.

**Comment by phillipviana** [comment]
Hi Douglas.

I apologize for the late reply. Your proposed solution worked perfectly, thank you.

Yes, I think it should be the default behavior :) Intuitively I expected xsbt-web-plugin to 'seamlessly' replace the jar packaging with the war packaging. So when I realized that the manifest in the war file didn't contain the very same attributes as the jar, I thought it was a defect in the plugin.

Again, it's the impression of someone totally new to sbt and xsbt-web-plugin. But here are my two cents.

**Comment by earldouglas** [comment]
> Your proposed solution worked perfectly, thank you

Great to hear!

> Intuitively I expected xsbt-web-plugin to 'seamlessly' replace the jar packaging with the war packaging

That makes sense.  Actually xsbt-web-plugin *adds* a *.war* package in addition to the *.jar* package that would normally contain all the classes and resources.

But I agree, it makes sense that if there are manifest attributes in the *.jar* file, many folks would also want them in the *.war* file.  Perhaps this should be a setting that defaults to true.  Something like:

```scala
inheritJarManifest := true // or false
```

**Comment by phillipviana** [comment]
Makes sense to me!

**Comment by earldouglas** [comment]
This is [now available via `inheritJarManifest`][1] in xsbt-web-plugin version 2.2.0.

[1]: https://github.com/earldouglas/xsbt-web-plugin/blob/master/docs/2.2.md#inherit-manifest-attributes
