### ISSUE TITLE
Specify context path for Tomcat deployment

### ISSUE THREAD

**Issue by rajarshi** [earldouglas/xsbt-web-plugin#294]
When running a webapp with tomcat (~tomcat:start) is there a way to specify the contextPath, which by default is '/'. The README seems to provide a way to do it for Jetty

**Comment by earldouglas** [comment]
I don't think there's a way to do this directly right now -- you'd need to get raw access to the command-line args that are sent to the Tomcat runner.

You can do this manually with not too much work, by skipping `TomcatPlugin` and going directly through `ContainerPlugin`:

*build.sbt:*

```scala
enablePlugins(ContainerPlugin)

containerLibs in Container := Seq(
  ("com.github.jsimone" % "webapp-runner" % "7.0.34.1").intransitive()
)

containerLaunchCmd in Container := Seq(
  "webapp.runner.launch.Main",
  "--port", "8181",
  "--path", "/foobar",
  (target in webappPrepare).value.absolutePath
)
```

For a full list of options, see here: https://github.com/jsimone/webapp-runner#options

**Comment by earldouglas** [comment]
Note: for the above, you'll need to use `container:start` and `container:stop` rather than `tomcat:start` and `tomcat:stop`.

**Comment by rajarshi** [comment]
Thanks a lot!

**Comment by earldouglas** [comment]
> I don't think there's a way to do this directly right now

Oh, I'm dumb -- I completely forgot about `containerArgs`:

```scala
enablePlugins(TomcatPlugin)

containerArgs := Seq("--path", "/foobar")
```

Now use `tomcat:start` to start your webapp with the context path `/foobar`.

I'll add this to the readme.

**Comment by rajarshi** [comment]
Many thanks - much simpler and works fine
