### ISSUE TITLE
on windows, jetty locks static content files

### ISSUE THREAD

**Issue by nazoking** [earldouglas/xsbt-web-plugin#297]
http://www.eclipse.org/jetty/documentation/current/troubleshooting-locked-files-on-windows.html

when run server and restart it, sbt say

```
[error] (*:webappPrepare) java.io.FileNotFoundException: C:\Users\nazoking\git\gitbucket\target\webapp\assets\common\css\gitbucket.css (要求された操作はユーザー マップ セクションで開いたファイルでは実行できません。)
[error] Total time: 3 s, completed Jan 12, 2016 5:34:32 PM
```

「ユーザー マップ セクションで開いたファイルには要求された操作を実行できません」is 'The requested operation cannot be performed on a file with a user-mapped section open' in english.

This problem was resolved on https://github.com/earldouglas/xsbt-web-plugin/issues/156 version 0.9 .
But, after version 1.0, it returned. ( I use version 2.1.0 )

Now, I solve it by that edit my WEB-INF/web.xml .
But, it method effect all users and product system .

**Comment by earldouglas** [comment]
Thanks for the report.  I'll look right into it.

**Comment by earldouglas** [comment]
Since we're now using jetty-runner to launch via a forked JVM, resolving this issue will be tricky.  We no longer have direct access to a `Context` into which we can inject init-params.

One approach would be to set `useFileMappedBuffer=false` in a `webdefaults.xml` file that we pull in via a `jetty.xml`.  This feels pretty awkward, but might be the most idiomatic solution.

**Comment by earldouglas** [comment]
The simplest solution, detailed on the link above, seems to be configuring the default Jetty Servlet directly in your web.xml:

*web.xml:*

```xml
  <servlet>
    <servlet-name>default</servlet-name>
    <servlet-class>org.mortbay.jetty.servlet.DefaultServlet</servlet-class>
    <init-param>
      <param-name>useFileMappedBuffer</param-name>
      <param-value>false</param-value>
    </init-param>
    <load-on-startup>0</load-on-startup>
  </servlet>
```

Closing this one, since it's an issue with jetty-runner and Windows, and outside the scope of xsbt-web-plugin.
