### ISSUE TITLE
Latest version not in a public repository

### ISSUE THREAD

**Issue by adrian-wang** [earldouglas/xsbt-web-plugin#299]
There's a lot of great work here, I can see there are many useful features in 2.x. But I cannot find any version later than 0.9.1 of this plugin in any repository, did I miss something?

**Comment by earldouglas** [comment]
Since 1.0, xsbt-web-plugin has been hosted on bintray, per sbt's standard.

**Comment by earldouglas** [comment]
If you're interested in browsing the repo manually, check out [https://bintray.com/earldouglas/sbt-plugins/xsbt-web-plugin](https://bintray.com/earldouglas/sbt-plugins/xsbt-web-plugin).

**Comment by adrian-wang** [comment]
Oh, thanks for the answer here.
