### ISSUE TITLE
Command to start Tomcat in debug mode

### ISSUE THREAD

**Issue by joeytsaiexpedia** [earldouglas/xsbt-web-plugin#301]
After reading issue [225], I want to create a command to start Tomcat in debug mode.  Although the documented example of adding javaOptions to build.sbt works, I don't want to always have remote debugging on.  The response in 225 was to create a command that refers to the container plugin, but this doesn't work with the TomcatPlugin.

To use the referenced solution:

```
def debugTomcat = Command.command("debugTomcat") { state =>
  val state2 = Project.extract(state).append(Seq(javaOptions in Tomcat += "-Dfoo=bar"), state)
  Project.extract(state2).runTask(start in tomcat, state2)
  state
}
```

this fails with:

```
error: not found: value start
  Project.extract(state2).runTask(start in Tomcat, state2)
                                  ^
```

Two requests, 1) how do I create a similar sbt command which works with TomcatPlugin and 2) to repeat @DavidPerezIngeniero, please provide a command to start the container with remote debugging enabled. Nearly everybody needs this.

**Comment by earldouglas** [comment]
> 1) how do I create a similar sbt command which works with TomcatPlugin

Something like this ought to work:

```scala
def debugTomcat = Command.command("debugTomcat") { state =>
  import com.earldouglas.xwp.ContainerPlugin.start
  val javaOpts =
    Seq(
      "-Xdebug",
      "-Xrunjdwp:server=y,transport=dt_socket,address=4000,suspend=n"
    )
  val state2 =
    Project.extract(state).append(
      Seq(javaOptions in Tomcat ++= javaOpts),
      state
    )
  Project.extract(state2).runTask(start in Tomcat, state2)
  state
}

commands += debugTomcat
```

> 2) to repeat @DavidPerezIngeniero, please provide a command to start the container with remote debugging enabled. Nearly everybody needs this.

What would you propose as the new command?  Should there be a toggleable setting in conjunction with `tomcat:start`, or perhaps a new command `tomcat:debug`?  If the latter, how would one configure the specific debug settings?  A new key such as `debugOptions: Seq[String]`?

**Comment by joeytsaiexpedia** [comment]
Thanks for your response!  So the command works, but now my tomcat server doesn't exit, surviving tomcat:stop and even after exiting sbt itself.  (Right now I'm just killing the spawned process).

As a user of this plugin (which is great, btw) I think tomcat:debug has the best ergonomics and would fit in well with the existing :stop and :join commands.  The corresponding debugOptions key also makes sense.  Thanks again for the your reply!

**Comment by joeytsaiexpedia** [comment]
Changing "state" to "state2" as the last line of the Command allows Tomcat to exit after a  tomcat:stop or exiting from sbt.  Quick question - does that change to your Command make sense?  (I returned "state" as that was used in Issue #225

**Comment by earldouglas** [comment]
Oh cool, nice catch!

**Comment by earldouglas** [comment]
This is [now available][1] via `tomcat:debug` in xsbt-web-plugin version 2.2.0.

[1]: https://github.com/earldouglas/xsbt-web-plugin/blob/master/docs/2.2.md#debug-mode
