### ISSUE TITLE
Log an error if sbt version < 0.13.5 is being used with version >= 2.0.0

### ISSUE THREAD

**Issue by joshlemer** [earldouglas/xsbt-web-plugin#303]
Is it possible to have xsbt-web-plugin create an error if it detects the sbt version to be incompatably old? 
I think it could help save people time in the future.

**Comment by earldouglas** [comment]
That's a great idea.  I don't know if there's a way to tell sbt to enforce this, but it might be doable through [`s.configuration.provider.id.version`](https://github.com/sbt/sbt/blob/6b6fd305ff7aab36ce2daad918c534ff9bdaf737/main/src/main/scala/sbt/Main.scala#L114).
