### ISSUE TITLE
TomcatPlugin conflicts in classpath

### ISSUE THREAD

**Issue by joeytsaiexpedia** [earldouglas/xsbt-web-plugin#304]
Using the Tomcat plugin appears to put webapp-runner.jar into my classpath.  This jar appears to bundle netty, which causes a conflict with my own dependencies - I'm also transitively depending on netty. This results in IllegalAccessError or NoSuchMethodError.  Any thoughts on how to resolve these library conflicts?

**Comment by joeytsaiexpedia** [comment]
Here's a post with a similar issue (http://deploymentzone.com/2014/08/19/netty-and-the-datastax-cassandra-driver/)

And here's a general article about the woes of embedded app servers =/ (http://steveperkins.com/war-files-vs-embedded-servers/)

**Comment by earldouglas** [comment]
I'm a little surprised that this is happening.  The `webapp-runner.jar` dependency should be included intransitively, and is appended to the forked JVM's classpath at the end of the list of your own dependencies.

Any chance you can provide a small example to reproduce the issue?  It would be a big help in debugging this one.
