### ISSUE TITLE
Unable to include multiple typesafe configurations 

### ISSUE THREAD

**Issue by joshuafernandes** [earldouglas/xsbt-web-plugin#306]
Hello,

I have a question regarding making war files with multiple typesafe 'application.conf' equivalent files. My app has one base application.conf file (common settings) and a development.conf, test.conf and production.conf (individual profiles and overrides) that include application'. In the main class I did:
    
    val config = ConfigFactory.defaultApplication

and to run I passed in a profile like so:

   sbt -Dconfig.resource=development.conf clean compile run

After adding the xsbt plugin I've been unable to switch profiles or do anything like that. It seems to only pick up on the single application.conf file and disregards the property being passed in, consequently it raises errors saying config isnt found. Is there some conflict somewhere or should I be doing something differently to get this working? Id like to be able to preserve the profiles rather than have to put everything in one file and swap for production. Id really appreciate it if someone could shed some light on this or point me in the right direction.

Thanks

Cheers
Josh

**Comment by earldouglas** [comment]
I'm not familiar with Typesafe configuration.  Can you provide a sample project to reproduce the problem?  If not, that's ok, but it will take me a little while to get up to speed.

**Comment by joshuafernandes** [comment]
Sure thing, I'll try and get something whipped up and put it on github and
put a link for you

**Comment by joshuafernandes** [comment]
@earldouglas: here's a link to a base project I created: `https://github.com/joshuafernandes/base`

So I define multiple config files (development.conf/ production.conf /etc) that all include the base 'application.conf' and can use them depending on environment. I run development specific settings with

`sbt -Dconfig.resource=development.conf clean compile run`

and so on. Problem is when I try to convert it to package as a war I loose this functionality. Is there something similar that can be done using the plugin?

Thanks for looking into this

**Comment by earldouglas** [comment]
Thanks for the example!  Taking a look now.

**Comment by earldouglas** [comment]
Your example project doesn't appear to use xsbt-web-plugin.  What mechanism are you using to convert it to a *.war* file?

**Comment by joshuafernandes** [comment]
Have put it on a branch called 'tomcat'

To run In development Im using:

`sbt -Dconfig.resource=development.conf clean compile tomcat:start shell`

And it throws errors saying config vars cannot be found. Im unsure of how to sort this out. After hours of playing around I discovered it reads env vars, but not system properties, would really like to know what Im doing wrong here

**Comment by earldouglas** [comment]
The problem is that you're passing the `config.resource` option to sbt's JVM, but running `tomcat:start` forks the JVM and runs your webapp in a new process, which doesn't replicate the option.

All you need to do is add `javaOptions += "-Dconfig.resource=development.conf"` to your project's settings.

You can have two options.

**Option 1:**

Add this to your *project/Build.scala* file:

```scala
val project = Project (
  id = "base" ,
  base = file("."),
  settings = Defaults.coreDefaultSettings ++
    Seq(
      organization := "com.example",
      name := "base",
      version := versions("base"),
      scalaVersion := versions("scala"),
      libraryDependencies ++= appDependencies,
      javaOptions += "-Dconfig.resource=development.conf"
    )
).enablePlugins(TomcatPlugin)
```

**Option 2:**

Add this setting to your launch command:

```
sbt 'set javaOptions += "-Dconfig.resource=development.conf"' clean compile tomcat:start shell
```

**Comment by joshuafernandes** [comment]
Right, thanks :)

The second will do fine :+1:
