### ISSUE TITLE
Need a way to increase cacheMaxSize

### ISSUE THREAD

**Issue by vvass** [earldouglas/xsbt-web-plugin#317]
I love this plugin and have been using it for a while. I have recently upgraded some of my libraries (I have avoided the scala and sbt versions mentioned in the docs 2.11 and 2.12). Currently I would like to know a way to make the cacheMaxSize bigger. I can do that with a tomcat instance on my local machine but then I wont be using this plugin. Please let me know if you have any ideas?

**Comment by earldouglas** [comment]
Glad to hear that you find the plugin useful!

It looks like [`cacheMaxSize` is set in the `Context` element](https://tomcat.apache.org/tomcat-8.0-doc/config/resources.html#Common_Attributes) of Tomcat's *context.xml*.

> I can do that with a tomcat instance on my local machine

If you already have a *context.xml* that you can set this configuration in, you can configure xsbt-web-plugin to tell the container to use it via `containerArgs`.

*build.sbt:*

```scala
containerArgs := Seq("--context-xml", "/path/to/context.xml")
```

**Comment by vvass** [comment]
That worked perfectly. Thank you.
