### ISSUE TITLE
Not reloaded when modifying src/main/webapp with sbt 1.0.3

### ISSUE THREAD

**Issue by takezoe** [earldouglas/xsbt-web-plugin#355]
- sbt: 1.0.3
- xsbt-web-plugin: 4.0.0

Start my app by `sbt ~jetty:start` and modify resources under `src/main/webapp`, but never reloaded. It works for `src/main/scala` with no problem.

With sbt 0.13.15, it works for `src/main/webapp` as well.

**Comment by earldouglas** [comment]
Thanks for the report.  It looks like this problem is happening with sbt 1.0.0 and above.

**Comment by earldouglas** [comment]
The fix for this has been released in version 4.0.1.

**Comment by takezoe** [comment]
Thanks!
