### ISSUE TITLE
Artifacts aren't recreated after manual deletion

### ISSUE THREAD

**Issue by mrArkwright** [earldouglas/xsbt-web-plugin#376]
If I manually delete `target/webapp` or `target/webapp-quick` or any of its contents, invoking `webappPrepare` (and `webappPrepareQuick` respectively) doesn't recreate the deleted files.

The culprit seems to be in the `cacheify` function. `outChanges` isn't consulted for differences in the cache and the destination directory. `outChanges.modified` should contain the files that aren't present in the destination anymore and should be copied there again. Also as of my understanding the `action` function passed to `FileFunction.cached` needs to return a list of all files added to the destination directory and not only the ones added in the last run, for caching to work properly.

As a quick workaround deleting `target/streams/_global/webappPrepare` (and `webappPrepareQuick` respectively) forces a complete rebuild of the destination directories.

**Comment by earldouglas** [comment]
Thanks, this is very helpful!
