### ISSUE TITLE
How to enable modules for Jetty?

### ISSUE THREAD

**Issue by softshipper** [earldouglas/xsbt-web-plugin#406]
Hi all 
In Jetty, there is a possibility to activate some modules. For instance, I have activated the following modules:

```
Enabled Modules:
================
   14) webapp          transitive provider of webapp for plus
                       transitive provider of webapp for deploy
                       init template available with --add-to-start=webapp
   15) plus            transitive provider of plus for annotations
   16) annotations     transitive provider of annotations for websocket
                       transitive provider of annotations for jsp
   17) apache-jsp      transitive provider of apache-jsp for jsp
   18) apache-jstl     transitive provider of apache-jstl for jstl
   19) client          transitive provider of client for websocket
   20) deploy          ${jetty.base}/start.d/start.ini
   21) home-base-warning ${jetty.base}/start.d/start.ini
   22) http            ${jetty.base}/start.d/start.ini
   23) jsp             ${jetty.base}/start.d/start.ini
   24) jstl            ${jetty.base}/start.d/start.ini
   25) keycloak        ${jetty.base}/start.d/keycloak.ini
   26) servlets        ${jetty.base}/start.d/start.ini
   27) websocket       ${jetty.base}/start.d/start.ini

```
Is it also possible to enable some modules on the plugin? 

Thanks

**Comment by earldouglas** [comment]
Can you tell me more about how you activated these modules?  I would assume that the same is possible with xsbt-web-plugin, since it simply delegates to [jetty-runner](http://www.eclipse.org/jetty/documentation/current/runner.html).

**Comment by softshipper** [comment]
Hi @earldouglas 
What I mean is https://www.eclipse.org/jetty/documentation/current/startup-modules.html. Look at the section Configuring Modules. When I run jetty without jetty-runner, it allows me to enable modules.   

Thanks

**Comment by earldouglas** [comment]
Thanks for the link.  Reading through that, I don't see a way to do it with jetty-runner.  There might be a way to map those *.ini* files to a *jetty.xml* file, but it's beyond my knowledge of Jetty configuration.  It might be easier to write a custom xsbt-web-plugin container that uses a local (or Docker) installation of Jetty, bringing with it any modules you have installed.

**Comment by softshipper** [comment]
@earldouglas Thanks for clarification.

**Comment by earldouglas** [comment]
In case it helps, here's how to use a local Jetty installation from xsbt-web-plugin.  Since you already have a Jetty installation, you can probably skip steps 1 and 2.

1. Grab a copy of Jetty from https://www.eclipse.org/jetty/download.html
    ```
    cd /home/james/Downloads
    wget https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.30.v20200611/jetty-distribution-9.4.30.v20200611.tar.gz
    ```
2. Extract it
    ```
    cd /home/james
    tar -xzf Downloads/jetty-distribution-9.4.30.v20200611.tar.gz
    ```
3. Create a new xsbt-web-plugin project
    ```
    cd /home/james
    sbt new earldouglas/xsbt-web-plugin.g8 --name=example
    ```
4. Update the project configuration

    */home/james/example/build.sbt:*
    ```scala
    scalaVersion := "2.12.11"
    
    libraryDependencies += "javax.servlet" % "javax.servlet-api" % "3.1.0" % "provided"
    
    enablePlugins(ContainerPlugin)
    
    lazy val jettyHome = "/home/james/jetty-distribution-9.4.30.v20200611"
    
    target in webappPrepare := file(jettyHome) / "webapps" / moduleName.value
    
    containerForkOptions := ForkOptions().withWorkingDirectory(file(jettyHome))
    
    containerLaunchCmd in Container := { (port, path) =>
      Seq(
        "-jar",
        s"${jettyHome}/start.jar",
        s"jetty.http.port=${port}"
      )
    }
    ```
5. Run it with `container:start`
    ```
    cd /home/james/example
    sbt
    container:start
    ```
6. See it running at <http://localhost:8080/example/>

There's probably a better way to do this by separating Jetty base from Jetty home, but this is a start.

**Comment by magnolia-k** [comment]
Since jetty-distribution is no longer provided in Jetty 10 and later, and only jetty-home is provided, the procedure should be to use jetty-home.
