### ISSUE TITLE
Grpc support

### ISSUE THREAD

**Issue by paualarco** [earldouglas/xsbt-web-plugin#413]
Hello,

Thanks for creating this project, is great! 

Wanted to know if the plugin also supports grpc.

And in case it does, would additional configuration be needed?   (I can not see any references on the docs)

**Comment by earldouglas** [comment]
gRPC support is outside the scope of xsbt-web-plugin, and would depend on the choice of servlet container.  Out of the box, xsbt-web-plugin has support for Jetty 9 and Tomcat 9.  Neither of these support gRPC as far as I know.

Do you know if any servlet containers currently support gRPC?  If so, you can find instructions for using a different servlet container [here][1].

[1]: https://github.com/earldouglas/xsbt-web-plugin#custom-container

**Comment by paualarco** [comment]
It seems like gRPC should be supported on tomcat, see https://github.com/grpc/grpc-java/issues/6933 and https://github.com/grpc/grpc-java/pull/4738.
They are using java/spring, not sure if that would apply scala too :S

**Comment by paualarco** [comment]
Good news, I made it to deploy the grpc server in tomcat and now I can see the traffic. 

The way I have done it is by starting it asyncronously under the main class:

```
class MyServlet extends HttpServlet {
  Future(GrpcServer.start())
  override def doGet(req: HttpServletRequest, res: HttpServletResponse) {
    val responseBody: String =
      """|<html>
         |  <body>
         |    <h1>Hello, world!</h1>
         |  </body>
         |</html>""".stripMargin
    res.getWriter.write(responseBody)
  }
}
```

However, the _grpc server_ only starts after the first http call (when the httpserverlet is created), but ideally it would initialise at the same time as the tomcat server does.  

Do you know if there is a good way of achieving that?

**Comment by earldouglas** [comment]
Oh cool!  Nice work getting this going.  Are you using the bundled container, or a custom/later one?

To get the gRPC server to start, you need the container to eagerly instantiate your `MyServlet`, so that the `Future(GrpcServer.start())` line will run during its construction.  To do this, just add a `<load-on-startup>` element to the `<servlet>` element in *web.xml*:

```xml
<servlet>
  <servlet-name>MyServlet</servlet-name>
  <servlet-class>com.example.MyServlet</servlet-class>
  <load-on-startup>1</load-on-startup>
</servlet>
```

**Comment by paualarco** [comment]
Awesome! Thanks :D
I am using the `Tomcat` one
