### ISSUE TITLE
issue on tomcat server

### ISSUE THREAD

**Issue by hi-rullah** [earldouglas/xsbt-web-plugin#673]
when the TomcatPlugin enabled, compile command works. After that either tomcat:start or package command got stuck on command line. 
webappprepare 0s appears on the command line and just waiting endless.

**Comment by hi-rullah** [comment]
windows 10 OS, Java 11 and sbt 1.6.2

**Comment by earldouglas** [comment]
Thanks; I will see if I can reproduce.

**Comment by earldouglas** [comment]
This should be fixed by #933, which will be included in version 5.0.0.
