### ISSUE TITLE
Support for JDK17 compiled war files

### ISSUE THREAD

**Issue by fliu-123** [earldouglas/xsbt-web-plugin#734]
Hi, I am digging into ways to go from JDK11 to JDK 17 using the xsbt-web-plugin enabled sbt package. However, it looks that the plugin is using jetty 9.4 and when I compiled the project in JDK 17 and the war file is loaded. Jetty 9.4 complaint as below:
"java.lang.IllegalArgumentException: Unsupported class file major version 61"
It looks that the JDK17 is not perfectly supported by Jetty 9.4. So, it would be great to have the plugin to support newer versions such as 10 or 11 as well.
I looked at the container option and found that the ` "test" %% "runner" ... ` dependency in the README does not exist. Even if we need to rename the annotation from javax to jakarta for servlet 5 API, we are willing to do it and get the JDK 17 improvements.
Really appreciate your time!

**Comment by fliu-123** [comment]
Found an alternative.

**Comment by earldouglas** [comment]
Glad to hear you found an alternative.  Could you share what you found, so we can capture it in the documentation?
