### ISSUE TITLE
Can we support jetty 11+

### ISSUE THREAD

**Issue by fliu-123** [earldouglas/xsbt-web-plugin#760]
Hi, I noticed that there is a sunset of JDK 11 active support in six months [here](https://endoflife.date/java). So, jetty 11+ that are native to JDK 17 are expected to be added in order for the environment to be supported in a better state. Do you have any timeline to support it in the near future?

**Comment by earldouglas** [comment]
Jetty 11 is already supported; it's just not the default.  I have added [an example of a Jetty 11 project](https://github.com/earldouglas/xsbt-web-plugin/tree/eb9fa534eedb1f8fa87529cb593543f672858c59/examples/jetty-11) to demonstrate.  The key differences are:

* In *build.sbt*, update the `servlet-api` dependency to 5.0:

    ```
    libraryDependencies += "jakarta.servlet" % "jakarta.servlet-api" % "5.0.0" % "provided"
    ```

*  In *build.sbt*, override the Jetty version by setting `containerLibs`:

    ```
    containerLibs in Jetty := Seq("org.eclipse.jetty" % "jetty-runner" % "11.0.14" intransitive())
    ```

* In the project's source code, replace `javax.servlet` with `jakarta.servlet`:

    ```
    import jakarta.servlet.http.HttpServlet
    import jakarta.servlet.http.HttpServletRequest
    import jakarta.servlet.http.HttpServletResponse
    ````

**Comment by fliu-123** [comment]
Great, thanks! I will close this issue then.
