### ISSUE TITLE
Prefilter/mapping for webapp resources

### ISSUE THREAD

**Issue by vendamere** [earldouglas/xsbt-web-plugin#791]
Is there a method for pre-filtering webapp resources prior to putting them into the cache?
I believe the current `_webappPrepare` method is grabbing everything and the only way to remove them is in the `webappPostProcess`. Dealing with them in post process is a bit expensive when they could be filtered ahead of time.

Perhaps adding something similar to `mappings` for the webapp resources would be a good way to address it.

**Comment by earldouglas** [comment]
Thanks for the suggestion!  You're right: `webappPostProcess` is the way to solve this currently.

I am working on a design for a more robust approach to gathering and preparing webapp resources that would support this use case (as well as eliminate the need for `webappPostProcess`).  I will update this issue with more info once I have a draft ready.

**Comment by earldouglas** [comment]
Fixed by #907.  Will be included in version 5.0.0.
